default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: junoym
  password: password
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: pre_reserve_database_development

test:
  <<: *default
  database: pre_reserve_database_test

production:
  <<: *default
  database: pre_reserve_database_production
  username: your_production_username
  password: <%= ENV['YOUR_DATABASE_PASSWORD'] %>
